#!/bin/sh

. "$HOME"/.xenv

inboxs=$(mktemp)
grep ^Inbox "$HOME"/.config/isyncrc >"$inboxs"

while read _ inbox; do
	mkdir -m 0700 -p "$inbox" &
done <"$inboxs"
wait

accounts=$(mktemp)
grep ^Account "$HOME"/.config/isyncrc >"$accounts"

while read _ account; do
	mbsync "$account" &
done <"$accounts"
wait


"$HOME"/.dotfiles/misc/mail-process
