[window]
opacity = 0.9
padding.x = 16
padding.y = 16

[font]
size = 16.0

[font.normal]
family = "JuliaMono"

[font.bold]
family = "JuliaMono"

[font.italic]
family = "JuliaMono"

[font.bold_italic]
family = "JuliaMono"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "-", mods = "Control|Shift", action = "DecreaseFontSize" }
]

[env]
TERM = "xterm-256color"

[colors.primary]
foreground = "#111111"
background = "#FFFFEA"

[colors.cursor]
text   = "#FFFFEA"
cursor = "#8B0000"

[colors.selection]
text       = "#111111"
background = "#AA9982"

[colors]
normal.red =     "#9E1020"
bright.red =     "#DA3B43"
normal.blue =    "#20109E"
bright.blue =    "#4066DC"
normal.cyan =    "#209E80"
bright.cyan =    "#49EAA8"
normal.black =   "#201020"
bright.black =   "#4A4A4A"
normal.green =   "#668820"
bright.green =   "#66A96A"
normal.white =   "#EAEAEA"
bright.white =   "#FFFFEA"
bright.yellow =  "#828200"
normal.yellow =  "#EA9E66"
bright.magenta = "#8066CC"
normal.magenta = "#9E20AE"
